# Generated by Django 4.1.7 on 2023-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
